version: "3"

networks:
  default:
    name: mynet
    external: true

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../../var/www/html:/code
    hostname: phpitbbackend
    networks:
      default:
        ipv4_address: 172.10.0.20

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ../../var/www/html:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    hostname: nginxitbbackend
    networks:
      default:
        ipv4_address: 172.10.0.21
